[conda]
disabled = true

[directory]
truncation_symbol = "â€¦/"
truncation_length = 8
truncate_to_repo = false

[status]
disabled = false
# style = 'bg:blue'
# symbol = 'ğŸ”´ '
# success_symbol = 'ğŸŸ¢ SUCCESS'
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# map_symbol = true

[git_branch]
always_show_remote = false

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_commit]
# commit_hash_length = 8
tag_disabled = false
tag_symbol = ' ğŸ”–'
tag_max_candidates = 0
only_detached = false

[git_metrics]
disabled = false

[memory_usage]
disabled = false
threshold = 70
format = "$symbol [${ram}( | ${swap})]($style) "

[python]
pyenv_version_name = false

[package]
format = 'via [ğŸ $version](208 bold) '

[custom.python_setuptools_scm]
# when = 'python -c "import setuptools_scm"'
# when = """python -c \"from importlib.util import find_spec; import sys; print( bool(find_spec(\"setuptools_scm\")))\" """
when = false
require_repo = true
command = 'python -m setuptools_scm'
